In [3]:
import numpy as np
import pandas as pd
import random
import matplotlib.pyplot as plt
%matplotlib inline

plt.rcParams["figure.figsize"] = (12,6)

# NumPy

**Задача 1**\
Сгенерировать массив из случайных положительных чисел произвольной длины. Вывести элементы, которые больше среднего арифметического.

In [22]:
arr1 = np.random.randint(1, 9999, size=np.random.randint(3, 10))
arr1

array([8850, 2893, 8285, 3539, 6118, 4128, 9972, 1385])

In [23]:
avg = np.mean(arr1)
avg

5646.25

In [24]:
arr1[arr1 > avg]

array([8850, 8285, 6118, 9972])

**Задача 2**\
Сгенерировать массив из 20 случайных элементов, элементы которого лежат в интервале [0, 10].
+ Определить количество элементов, отличающихся от минимального на 5.
+ Найти среднее арифметическое всех четных элементов массива, стоящих на нечетных местах.

In [63]:
arr2 = np.random.randint(11, size =20)
arr2

array([7, 6, 6, 0, 3, 5, 6, 2, 5, 4, 9, 5, 9, 8, 0, 4, 5, 5, 9, 9])

In [64]:
min_element = np.min(arr2)
min_element

0

In [65]:
diff_5 = np.sum(arr2 - min_element == 5)
diff_5

5

In [85]:
avg_even_odd = np.mean(arr2[1::2][arr2[1::2] % 2 == 0])
avg_even_odd

4.0

**Задача 3**\
Сгенерировать матрицу A размером 5 на 5, элементы которой лежат в интервале [1, 10].
+ Возвести в квадрат максимальный элемент матрицы.
+ Все четные числа заменить на 0.

In [102]:
matrix_a = np.random.randint(1, 11, size = (5, 5))
matrix_a

array([[ 3,  5,  9,  1,  6],
       [ 6,  5,  7,  6,  6],
       [ 4,  2,  5,  3,  6],
       [ 9,  8,  5,  7,  8],
       [ 3,  1,  9, 10,  8]])

In [103]:
max_element = np.max(matrix_a)
matrix_a[matrix_a == max_element] = max_element ** 2
matrix_a

array([[  3,   5,   9,   1,   6],
       [  6,   5,   7,   6,   6],
       [  4,   2,   5,   3,   6],
       [  9,   8,   5,   7,   8],
       [  3,   1,   9, 100,   8]])

In [104]:
matrix_a[(matrix_a % 2 == 0) & (matrix_a != max_element ** 2)] = 0
matrix_a

array([[  3,   5,   9,   1,   0],
       [  0,   5,   7,   0,   0],
       [  0,   0,   5,   3,   0],
       [  9,   0,   5,   7,   0],
       [  3,   1,   9, 100,   0]])

**Задача 4**\
Сгенерировать матрицу B размером 5 на 5, элементы которой лежат в интервале [-5, 5]. Отрицательные элементы матрицы заменить на число отрицательных элементов в строке, в которой они находятся.

In [110]:
matrix_b = np.random.randint(-5, 6, size = (5, 5))
matrix_b

array([[ 0,  3,  0,  4, -2],
       [ 1, -4,  1, -1, -4],
       [ 0,  5,  2, -2, -5],
       [-4,  5,  5,  4,  4],
       [-3,  0,  1, -1,  0]])

In [111]:
for i in range(matrix_b.shape[0]):
    neg_count = np.sum(matrix_b[i] < 0)
    matrix_b[i][matrix_b[i] < 0] = neg_count
matrix_b

array([[0, 3, 0, 4, 1],
       [1, 3, 1, 3, 3],
       [0, 5, 2, 2, 2],
       [1, 5, 5, 4, 4],
       [2, 0, 1, 2, 0]])

# Pandas

In [142]:
df = pd.read_csv("https://raw.githubusercontent.com/rolandmueller/titanic/main/titanic3.csv")

**Задание 1**
+ Какой была максимальная цена билета? Медиана?
+ Какова доля выживших?
+ Сколько мужчин / женщин находилось на борту?

In [132]:
df.head(3)

pclass  survived                            name     sex      age  sibsp  \
0       1         1   Allen, Miss. Elisabeth Walton  female  29.0000      0   
1       1         1  Allison, Master. Hudson Trevor    male   0.9167      1   
2       1         0    Allison, Miss. Helen Loraine  female   2.0000      1   

   parch  ticket      fare    cabin embarked boat  body  \
0      0   24160  211.3375       B5        S    2   NaN   
1      2  113781  151.5500  C22 C26        S   11   NaN   
2      2  113781  151.5500  C22 C26        S  NaN   NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON

In [191]:
df['fare'].max()

512.3292

In [192]:
df['fare'].median()

14.4542

In [127]:
survival_rate = df['survived'].mean()
survival_rate

0.3819709702062643

In [128]:
sex_counts = df['sex'].value_counts()
sex_counts

sex
male      843
female    466
Name: count, dtype: int64

In [130]:
sex_counts['male']

843

In [129]:
sex_counts['female']

466

**Задание 2**
+ Выведите распределение переменной __pclass__ для мужчин и женщин.
    + Сколько мужчин было в первом классе?
    + Сколько женщин было в третьем классе?
      
+ Создайте новый признак __age_group__, который равен:
    + 1, если пассажир был моложе 30 лет;
    + 2, если пассажиру было от 30 до 60 лет;
    + 3, если пассажир был старше 60 лет.

In [135]:
count_men_first_class = len(df[(df['pclass'] == 1) & (df['sex'] == 'male')])
count_men_first_class

179

In [136]:
count_women_first_class = len(df[(df['pclass'] == 3) & (df['sex'] == 'female')])
count_women_first_class

216

In [153]:
age_groups = []
for age in df['age']:
    if age <= 30:
        age_groups.append(1)
    elif age <= 60:
        age_groups.append(2)
    elif age > 60:
        age_groups.append(3)
    else:
        age_groups.append(None)

df['age_group'] = age_groups

In [154]:
df

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN   
1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  age_group  
0       NaN                     St Louis, MO        1.0  
1       NaN  Montreal, PQ / Chesterville, ON        1.0  
2       NaN  Montreal, PQ / Chesterville, ON        1.0  
3     135.0  Montreal, PQ / Chesterville, ON        1.0  
4       NaN  Montreal, PQ / Chesterville, ON        1.0  
...     ...                              ...        ...  
1304  328.0                              NaN        1.0  
1305    NaN                              NaN        NaN  
1306  304.0                              NaN        1.0  
1307    NaN                              NaN        1.0  
1308    NaN                              NaN        1.0  

[1309 rows x 15 columns]

**Задание 3**\
Найдите самое популярное имя среди пассажиров:
+ мужчин;
+ женщин.

In [162]:
df['first_name'] = df['name'].apply(lambda x: x.split(',')[1].split('.')[1].strip())
df.head(3)

pclass  survived                            name     sex      age  sibsp  \
0       1         1   Allen, Miss. Elisabeth Walton  female  29.0000      0   
1       1         1  Allison, Master. Hudson Trevor    male   0.9167      1   
2       1         0    Allison, Miss. Helen Loraine  female   2.0000      1   

   parch  ticket      fare    cabin embarked boat  body  \
0      0   24160  211.3375       B5        S    2   NaN   
1      2  113781  151.5500  C22 C26        S   11   NaN   
2      2  113781  151.5500  C22 C26        S  NaN   NaN   

                         home.dest  age_group        first_name  
0                     St Louis, MO        1.0  Elisabeth Walton  
1  Montreal, PQ / Chesterville, ON        1.0     Hudson Trevor  
2  Montreal, PQ / Chesterville, ON        1.0     Helen Loraine

In [164]:
df['first_name'][df['sex'] == 'male'].value_counts().sort_values(ascending=False).head(1)

first_name
John    15
Name: count, dtype: int64

In [165]:
df['first_name'][df['sex'] == 'female'].value_counts().sort_values(ascending=False).head(1)

first_name
Mary    7
Name: count, dtype: int64

**Задание 4**
+ Выведите данные о всех пассажирах, которые сели в Cherbourg (Embarked='C') и были старше 50 лет.
+ Выведите данные о всех женщинах младше 20 и старше 50 лет.
+ Сколько пассажиров старше 70 лет было на борту?

In [168]:
df[(df['embarked'] == 'C') & (df['age'] > 50)]

pclass  survived                                               name  \
9         1         0                            Artagaveytia, Mr. Ramon   
43        1         1    Bucknell, Mrs. William Robert (Emma Eliza Ward)   
48        1         1   Candee, Mrs. Edward (Helen Churchill Hungerford)   
50        1         1  Cardeza, Mrs. James Warburton Martinez (Charlo...   
78        1         1  Compton, Mrs. Alexander Taylor (Mary Eliza Ing...   
104       1         1                     Eustis, Miss. Elizabeth Mussey   
123       1         1                   Frolicher-Stehli, Mr. Maxmillian   
135       1         0                          Goldschmidt, Mr. George B   
136       1         1                          Gracie, Col. Archibald IV   
174       1         0                            Kent, Mr. Edward Austin   
186       1         1          Lindstrom, Mrs. Carl Johan (Sigrid Posse)   
192       1         1                               Lurette, Miss. Elise   
215       1         0                         Newell, Mr. Arthur Webster   
221       1         0                     Ostby, Mr. Engelhart Cornelius   
233       1         1      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)   
246       1         0                             Rothschild, Mr. Martin   
247       1         1     Rothschild, Mrs. Martin (Elizabeth L. Barrett)   
252       1         0                         Ryerson, Mr. Arthur Larned   
264       1         1                Simonius-Blumer, Col. Oberst Alfons   
267       1         0                            Smith, Mr. James Clinch   
276       1         0                      Spencer, Mr. William Augustus   
280       1         1                    Stengel, Mr. Charles Emil Henry   
282       1         1    Stephenson, Mrs. Walter Bertram (Martha Eustis)   
303       1         0                           Warren, Mr. Frank Manley   
304       1         1   Warren, Mrs. Frank Manley (Anna Sophia Atkinson)   
308       1         1              White, Mrs. John Stuart (Ella Holmes)   
316       1         0                        Williams, Mr. Charles Duane   

        sex   age  sibsp  parch    ticket      fare            cabin embarked  \
9      male  71.0      0      0  PC 17609   49.5042              NaN        C   
43   female  60.0      0      0     11813   76.2917              D15        C   
48   female  53.0      0      0  PC 17606   27.4458              NaN        C   
50   female  58.0      0      1  PC 17755  512.3292      B51 B53 B55        C   
78   female  64.0      0      2  PC 17756   83.1583              E45        C   
104  female  54.0      1      0     36947   78.2667              D20        C   
123    male  60.0      1      1     13567   79.2000              B41        C   
135    male  71.0      0      0  PC 17754   34.6542               A5        C   
136    male  53.0      0      0    113780   28.5000              C51        C   
174    male  58.0      0      0     11771   29.7000              B37        C   
186  female  55.0      0      0    112377   27.7208              NaN        C   
192  female  58.0      0      0  PC 17569  146.5208              B80        C   
215    male  58.0      0      2     35273  113.2750              D48        C   
221    male  65.0      0      1    113509   61.9792              B30        C   
233  female  56.0      0      1     11767   83.1583              C50        C   
246    male  55.0      1      0  PC 17603   59.4000              NaN        C   
247  female  54.0      1      0  PC 17603   59.4000              NaN        C   
252    male  61.0      1      3  PC 17608  262.3750  B57 B59 B63 B66        C   
264    male  56.0      0      0     13213   35.5000              A26        C   
267    male  56.0      0      0     17764   30.6958               A7        C   
276    male  57.0      1      0  PC 17569  146.5208              B78        C   
280    male  54.0      1      0     11778   55.4417             C116        C   
282  female  

In [172]:
df[(df['sex'] == 'female') & ((df['age'] < 20) | (df['age'] > 50))]

pclass  survived                                               name  \
2          1         0                       Allison, Miss. Helen Loraine   
6          1         1                  Andrews, Miss. Kornelia Theodosia   
8          1         1      Appleton, Mrs. Edward Dale (Charlotte Lamson)   
11         1         1  Astor, Mrs. John Jacob (Madeleine Talmadge Force)   
27         1         1            Bishop, Mrs. Dickinson H (Helen Walton)   
...      ...       ...                                                ...   
1265       3         0                          Van Impe, Miss. Catharina   
1273       3         0                 Vander Planke, Miss. Augusta Maria   
1279       3         0               Vestrom, Miss. Hulda Amanda Adolfina   
1300       3         1            Yasbeck, Mrs. Antoni (Selini Alexander)   
1304       3         0                               Zabour, Miss. Hileni   

         sex   age  sibsp  parch    ticket      fare    cabin embarked boat  \
2     female   2.0      1      2    113781  151.5500  C22 C26        S  NaN   
6     female  63.0      1      0     13502   77.9583       D7        S   10   
8     female  53.0      2      0     11769   51.4792     C101        S    D   
11    female  18.0      1      0  PC 17757  227.5250  C62 C64        C    4   
27    female  19.0      1      0     11967   91.0792      B49        C    7   
...      ...   ...    ...    ...       ...       ...      ...      ...  ...   
1265  female  10.0      0      2    345773   24.1500      NaN        S  NaN   
1273  female  18.0      2      0    345764   18.0000      NaN        S  NaN   
1279  female  14.0      0      0    350406    7.8542      NaN        S  NaN   
1300  female  15.0      1      0      2659   14.4542      NaN        C  NaN   
1304  female  14.5      1      0      2665   14.4542      NaN        C  NaN   

       body                        home.dest  age_group  \
2       NaN  Montreal, PQ / Chesterville, ON        1.0   
6       NaN                       Hudson, NY        3.0   
8       NaN              Bayside, Queens, NY        2.0   
11      NaN                     New York, NY        1.0   
27      NaN                     Dowagiac, MI        1.0   
...     ...                              ...        ...   
1265    NaN                              NaN        1.0   
1273    NaN                              NaN        1.0   
1279    NaN                              NaN        1.0   
1300    NaN                              NaN        1.0   
1304  328.0                              NaN        1.0   

                                 first_name  
2                             Helen Loraine  
6                        Kornelia Theodosia  
8            Edward Dale (Charlotte Lamson)  
11    John Jacob (Madeleine Talmadge Force)  
27               Dickinson H (Helen Walton)  
...                                     ...  
1265                              Catharina  
1273                          Augusta Maria  
1279                  Hulda Amanda Adolfina  
1300              Antoni (Selini Alexander)  
1304                                 Hileni  

[135 rows x 16 columns]

In [173]:
df[(df['age'] > 70)]['name'].count()

6

**Задание 5**
+ Посчитайте средний возраст среди мужчин и среди женщин.
+ Посчитайте доли выживших в различных возрастных группах (новый признак **AgeGroup**).
+ Найдите максимальную стоимость билета в каждом из ценовых классов.

In [174]:
df[(df['sex'] == 'male')]['age'].mean()

30.5852329787234

In [175]:
df[(df['sex'] == 'female')]['age'].mean()

28.6870706185567

In [176]:
df.groupby('age_group')['survived'].mean()

age_group
1.0    0.407225
2.0    0.423267
3.0    0.242424
Name: survived, dtype: float64

In [177]:
df.groupby('pclass')['fare'].max()

pclass
1    512.3292
2     73.5000
3     69.5500
Name: fare, dtype: float64

**Задание 6**\
Ответьте на предыдущие вопросы с помощью функции crosstab и метода pivot_table.

In [180]:
df.pivot_table(values='age', index='sex', aggfunc='mean')

age
sex              
female  28.687071
male    30.585233

In [188]:
pd.crosstab(df['age_group'], df['survived'])

survived     0    1
age_group          
1.0        361  248
2.0        233  171
3.0         25    8

In [190]:
df.pivot_table(values='fare', index='pclass', aggfunc='max')

fare
pclass          
1       512.3292
2        73.5000
3        69.5500